// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmhL8TF2B0zjl-lBDW2OpmYzrplsSDWg8',
    appId: '1:951317272452:web:8be52eb9c78c205a796fd1',
    messagingSenderId: '951317272452',
    projectId: 'flutter-store-a1670',
    authDomain: 'flutter-store-a1670.firebaseapp.com',
    storageBucket: 'flutter-store-a1670.appspot.com',
    measurementId: 'G-C6EY1Q5S8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJrgFAVcJD4rO_o_UvcXLGVcRueusYuhM',
    appId: '1:951317272452:android:5e37995bfb9e39f9796fd1',
    messagingSenderId: '951317272452',
    projectId: 'flutter-store-a1670',
    storageBucket: 'flutter-store-a1670.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZAIgqBSEq7_cNOtcczkw2NlKRA0qXQ9g',
    appId: '1:951317272452:ios:e7913343957469e2796fd1',
    messagingSenderId: '951317272452',
    projectId: 'flutter-store-a1670',
    storageBucket: 'flutter-store-a1670.appspot.com',
    androidClientId: '951317272452-ie947loekq2ho7snctic22e6kvdbr0um.apps.googleusercontent.com',
    iosClientId: '951317272452-pf4adbtf6oulk75bq3uc9l1mnmc7td42.apps.googleusercontent.com',
    iosBundleId: 'com.example.animatedLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZAIgqBSEq7_cNOtcczkw2NlKRA0qXQ9g',
    appId: '1:951317272452:ios:832b0e15e76d7dff796fd1',
    messagingSenderId: '951317272452',
    projectId: 'flutter-store-a1670',
    storageBucket: 'flutter-store-a1670.appspot.com',
    androidClientId: '951317272452-ie947loekq2ho7snctic22e6kvdbr0um.apps.googleusercontent.com',
    iosClientId: '951317272452-qd2p18rjsktnps6h8knimas0cf5up8vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.animatedLogin.RunnerTests',
  );
}
